token: "5440030440:AAGiPBn9JHb7VW60aRhf5S6HUqw6V8eEVgI"
channels:
  Волгоград:
      Охрана:
        id: "-1001675961636"
        link: "https://t.me/+IbKT55gmFFY3Mjli"
      Бар:
        id: "-1001749986535"
        link: "https://t.me/+39UtHLL-Io84ODFi"
      Арт:
        id: "-1001709159006"
        link: "https://t.me/+bmt4pt_U-xo0Mzhi"
      Админ:
        id: "-1001699370600"
        link: "https://t.me/+sCjHoRiemWNlOTVi"
  Москва:
      Охрана:
        id: "-1001697572469"
        link: "https://t.me/+lCSB8ONa-_A5MjBi"
      Бар:
        id: "-1001605922666"
        link: "https://t.me/+ZI_4oOBxTO1jMDAy"
      Арт:
        id: "-1001770807023"
        link: "https://t.me/+H0gKILCOoEZhNzI6"
      Админ:
        id: "-1001579885451"
        link: "https://t.me/+csVBWNTtOio1Yzgy"
  Краснодар:
      Охрана:
        id: "-1001633711454"
        link: "https://t.me/+RefSzW2YfyRiM2Qy"
      Бар:
        id: "-1001636988740"
        link: "https://t.me/+6ZIc6zsrSyA2MDEy"
      Арт:
        id: "-1001799331606"
        link: "https://t.me/+NfhguhhKwWlhMmZi"
      Админ:
        id: "-1001678631440"
        link: "https://t.me/+UUluhUnk4tZhYTIy"